apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-app
        image: docker.io/frederickyapiter/fe-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "54Mi"
            cpu: "100m"
        ports:
        - containerPort: 80