name: Publish docker image

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t frederickyapiter/fe-app:${{ github.sha }} .

      - name: Push image
        run: docker push frederickyapiter/fe-app:${{ github.sha }}

      - name: Clone k8s repo
        run: |
          git clone https://github.com/FrederickYapiter2411/k8s-stocker.git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          cd /k8s-stocker
          sed -i "s|image: frederickyapiter/fe-app:.*|image: frederickyapiter/fe-app:${{ github.sha }}|g" fe-deployment.yml
          git add k8s/fe-deployment.yml
          git commit -m "chore: update fe-app image to ${{ github.sha }}"
          git push


      # - name: Update image tag in Kubernetes manifest
      #   run: |
      #     sed -i "s|image: frederickyapiter/fe-app:.*|image: frederickyapiter/fe-app:${{ github.sha }}|g" k8s/fe-deployment.yaml

      # - name: Commit and push manifest changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add k8s/fe-deployment.yaml
      #     git commit -m "chore: update fe-app image to ${{ github.sha }}"
      #     git push